use_frameworks!
platform :ios, '10.0'
swift_version = '3.2'

target 'VideoPipelineKit_Example' do
  pod 'VideoPipelineKit', :path => '../'
  pod 'YUCIHighPassSkinSmoothing'

  target 'VideoPipelineKit_Tests' do
    inherit! :search_paths
  end
end
